name: Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.mdx"
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**.mdx"

jobs:
  Test-Package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
